v8

diff --git a/system/bin/debloat b/system/bin/debloat
--- a/system/bin/debloat
+++ b/system/bin/debloat
@@ -41,6 +41,7 @@ set_busybox() {
       fi
     done
     _busybox=true
+    _bb=$1
   fi
 }
 if [ ! -x $SYSTEM/xbin/busybox ]; then
@@ -56,8 +57,10 @@ if [ ! -x $SYSTEM/xbin/busybox ]; then
 fi
 if [ -x $SYSTEM/xbin/busybox ]; then
   true
+  _bb=$SYSTEM/xbin/busybox
 elif [ -x $SYSTEM/bin/busybox ]; then
   true
+  _bb=$SYSTEM/bin/busybox
 elif [ -x /data/data/com.topjohnwu.magisk/busybox/busybox ]; then
   export PATH=$PATH:/data/data/com.topjohnwu.magisk/busybox
 elif [ $_busybox ]; then
@@ -68,6 +71,11 @@ else
   false
 fi
 [ $? -ne 0 ] && exit $?
+_bbname=$(busybox | head -n1)
+_bbname=${_bbname%'('*}
+if [ "$_bbname" == "" ]; then
+  _bbname="BusyBox not found!"
+fi
 
 #=========================== Default Functions
 
@@ -94,19 +102,18 @@ mktouch() {
   chmod 644 $1
 }
 
-# runl <cmd>
-runl() {
-  echo "[$(date +"%F %T")]: $@" >> $LOG 2>>$LOG
-  $@ 2>>$LOG
-  return $?
-}
-
 #=========================== Default Variables
 # > Stuff here is used for some other stuff
 # > Edit only if necessary!
 
 # Magisk Mod Directory
-MODDIR="/magisk/$ID"
+MOUNTPATH=/magisk
+if [ ! -d $MOUNTPATH ]; then
+  if [ -d /sbin/.core/img ]; then
+    MOUNTPATH=/sbin/.core/img
+  fi
+fi
+MODDIR="$MOUNTPATH/$ID"
 if [ ! -d $MODDIR ]; then
   if [ -d /sbin/.core/img/$ID ]; then
     MODDIR=/sbin/.core/img/$ID
@@ -150,6 +157,9 @@ clear
 echo "$div"
 echo "${W}$MODTITLE $VER${N}${Bl}($REL)${N}"
 echo "by ${W}$AUTHOR${N}"
+echo "$div"
+echo "${W}$_bbname${N}"
+echo "${Bl}$_bb${N}"
 echo "$div"
 
 show_rein=0
@@ -257,7 +267,7 @@ echo " d - ${C}Donate${N}"
 echo " 0 - ${Bl}Exit${N}"
 echo ""
 echo -n "[CHOICE]: "
-runl read choice
+read choice
 if [ "$choice" == "1" ]; then
   if [ -d $SYSTEM/app ]; then
     clear
@@ -277,14 +287,14 @@ if [ "$choice" == "1" ]; then
     echo " 0 - ${Bl}Exit${N}"
     echo "$div"
     echo -n "[CHOICE]: "
-    runl read app
+    read app
     if [ "$app" == m ]; then
       echo "Choose numbers listed above."
       echo "Do not repeat the same number."
       echo " 0 - Proceed to Uninstall choices"
       echo -n " > "
       c=1
-      while runl read app; do
+      while read app; do
         if [ "$app" == 0 ]; then
           break
         fi
@@ -295,13 +305,13 @@ if [ "$choice" == "1" ]; then
         busybox printf " > "
       done
       if [ "${#multiple[@]}" == 0 ]; then
-        runl echo "No app chosen"
-        runl exit 1
+        echo "No app chosen"
+        exit 1
       else
         c=1
         for i in ${multiple[@]}; do
-          runl echo "Uninstalling ${R}${app_name[${choice[$c]}]}${N}" | tr '_' ' '
-          runl mktouch $i/.replace ${app_name[${choice[$c]}]}
+          echo "Uninstalling ${R}${app_name[${choice[$c]}]}${N}" | tr '_' ' '
+          mktouch $i/.replace ${app_name[${choice[$c]}]}
           if [ "${app_label[${choice[$c]}]}" ]; then
             data_apkdir=$(echo /data/app/${app_label[${choice[$c]}]}-*)
             if [ -d ${data_apkdir} ]; then
@@ -311,17 +321,17 @@ if [ "$choice" == "1" ]; then
           sleep 0.5
           c=$((c+1))
         done
-        runl exit
+        exit
       fi
     elif [ "$app" -gt ${#app[@]} ] || [ "$app" -lt 0 ] || [ "$app" == "" ] || [ -n "$(echo $app | tr -d '0-9')" ] ; then
-      runl echo "Invalid"
-      runl exit 1
+      echo "Invalid"
+      exit 1
     elif [ "$app" == "0" ]; then
-      runl exit
+      exit
     else
-      runl echo "Uninstalling ${R}${app_name[$app]}${N}" | tr '_' ' '
+      echo "Uninstalling ${R}${app_name[$app]}${N}" | tr '_' ' '
       sleep 1
-      runl mktouch $MODDIR${app[$app]}/.replace ${app_name[$app]}
+      mktouch $MODDIR${app[$app]}/.replace ${app_name[$app]}
       if [ "${app_label[$app]}" ]; then
         data_apkdir=$(echo /data/app/${app_label[$app]}-*)
         if [ -d ${data_apkdir} ]; then
@@ -329,11 +339,11 @@ if [ "$choice" == "1" ]; then
         fi
       fi
       echo "Reboot to apply changes"
-      runl exit
+      exit
     fi
   else
-    runl echo Invalid
-    runl exit 1
+    echo Invalid
+    exit 1
 	fi
 elif [ "$choice" == 2 ]; then
   if [ -d $SYSTEM/priv-app ]; then
@@ -354,14 +364,14 @@ elif [ "$choice" == 2 ]; then
     echo " 0 - ${Bl}Exit${N}"
     echo "$div"
     echo -n "[CHOICE]: "
-    runl read privapp
+    read privapp
     if [ "$privapp" == m ]; then
       echo "Choose numbers listed above."
       echo "Do not repeat the same number."
       echo " 0 - Proceed to Uninstall choices"
       echo -n " > "
       c=1
-      while runl read app; do
+      while read app; do
         if [ "$app" == 0 ]; then
           break
         fi
@@ -372,13 +382,13 @@ elif [ "$choice" == 2 ]; then
         busybox printf " > "
       done
       if [ "${#multiple[@]}" == 0 ]; then
-        runl echo "No app chosen"
-        runl exit 1
+        echo "No app chosen"
+        exit 1
       else
         c=1
         for i in ${multiple[@]}; do
-          runl echo "Uninstalling ${R}${app_name[${choice[$c]}]}${N}" | tr '_' ' '
-          runl mktouch $i/.replace ${app_name[${choice[$c]}]}
+          echo "Uninstalling ${R}${app_name[${choice[$c]}]}${N}" | tr '_' ' '
+          mktouch $i/.replace ${app_name[${choice[$c]}]}
           if [ "${app_label[${choice[$c]}]}" ]; then
             data_apkdir=$(echo /data/app/${app_label[${choice[$c]}]}-*)
             if [ -d ${data_apkdir} ]; then
@@ -388,17 +398,17 @@ elif [ "$choice" == 2 ]; then
           sleep 0.5
           c=$((c+1))
         done
-        runl exit
+        exit
       fi
     elif [ "$privapp" -gt ${#privapp[@]} ] || [ "$privapp" -lt 0 ] || [ "$privapp" == "" ] || [ -n "$(echo $privapp | tr -d '0-9')" ] ; then
-      runl echo "Invalid"
-      runl exit 1
+      echo "Invalid"
+      exit 1
     elif [ "$privapp" == "0" ]; then
-      runl exit
+      exit
     else
-      runl echo "Uninstalling ${R}${app_name[$privapp]}${N}" | tr '_' ' ' 
+      echo "Uninstalling ${R}${app_name[$privapp]}${N}" | tr '_' ' ' 
       sleep 1
-      runl mktouch $MODDIR${privapp[$privapp]}/.replace ${app_name[$privapp]}
+      mktouch $MODDIR${privapp[$privapp]}/.replace ${app_name[$privapp]}
       if [ "${app_label[$privapp]}" ]; then
         data_apkdir=$(echo /data/app/${app_label[$privapp]}-*)
         if [ -d ${data_apkdir} ]; then
@@ -406,11 +416,11 @@ elif [ "$choice" == 2 ]; then
         fi
       fi
       echo "Reboot to apply changes"
-      runl exit
+      exit
     fi
   else
-    runl echo Invalid
-    runl exit 1
+    echo Invalid
+    exit 1
   fi
 elif [ "$choice" == 3 ]; then
   if [ $show_rein == 1 ]; then
@@ -427,28 +437,28 @@ elif [ "$choice" == 3 ]; then
     echo -n "[CHOICE]: "
     read rein
     if [ "$rein" -gt ${#name_unin[@]} ] || [ "$rein" -lt 0 ] || [ "$rein" == "" ] || [ -n "$(echo $rein | tr -d '0-9')" ] ; then
-      runl echo "Invalid"
-      runl exit 1
+      echo "Invalid"
+      exit 1
     elif [ "$rein" == "0" ]; then
-      runl exit
+      exit
     else
-      runl echo "Reinstalling ${G}${name_unin[$rein]}${N}" | tr '_' ' '
+      echo "Reinstalling ${G}${name_unin[$rein]}${N}" | tr '_' ' '
       sleep 1
-      runl rm -rf ${unin_app[$rein]}
+      rm -rf ${unin_app[$rein]}
       echo "Reboot to apply changes"
-      runl exit
+      exit
     fi
   else
-    runl echo "Invalid"
-    runl exit 1
+    echo "Invalid"
+    exit 1
   fi
 
 elif [ "$choice" == "d" ] || [ "$choice" == "D" ]; then
-  runl am start https://paypal.me/veez21 >/dev/null
+  am start https://paypal.me/veez21 >/dev/null
 elif [ "$choice" == "0" ]; then
-  runl exit 
+  exit 
 else echo Invalid
-  runl exit 1
+  exit 1
 fi
 
-runl exit $?
+exit $?
