Fix run as root message
Signed-off-by: Val Mandantes <mandantesv@gmail.com>

diff --git a/system/bin/debloat b/system/bin/debloat
--- a/system/bin/debloat
+++ b/system/bin/debloat
@@ -7,7 +7,8 @@
 ID="terminal_debloater"
 
 # Detect root
-[[ $(id -u) -ne 0 ]] && { echo "$ID needs to be in as root!"; echo "type 'su' then '$_name'"; exit 1; }
+_name=$(basename $0)
+[[ $(id -u) -ne 0 ]] && { echo "$ID needs to run as root!"; echo "type 'su' then '$_name'"; exit 1; }
 
 # Magisk Mod Directory
 MOUNTPATH=/sbin/.core/img
@@ -73,7 +74,7 @@ MOUNT_LOOP=$(basename $(grep -m1 $MOUNTPATH /proc/mounts | awk '{print $1}'))
 debloat_app() {
 	[ "$1" == "n" ] && shift || get_cfg $1
 	if grep -w $DIR_APP /proc/mounts | grep -q $MOUNT_LOOP; then
-		echo "Failed! $DIR_APP is mounted!"
+		echo "Failed! $DIR_APP is mounted (by another Magisk Module)!"
 	else
 		echo "Uninstalling ${R}${1}${N} ($DIR_APP)" | tr '_' ' '
 		sleep 0.4
