v13

diff --git a/system/bin/debloat b/system/bin/debloat
--- a/system/bin/debloat
+++ b/system/bin/debloat
@@ -73,6 +73,8 @@ else
 	false
 fi
 [ $? -ne 0 ] && exit $?
+alias echo='echo -e'
+[ -n "$LOGNAME" ] && alias clear='clear && echo'
 _bbname=$(busybox | head -n1)
 _bbname=${_bbname%'('*}
 BBok=true
@@ -89,6 +91,7 @@ set_file_prop() {
 }
 
 # https://github.com/fearside/ProgressBar
+loadBar=' '
 ProgressBar() {
 # Process data
 	_progress=$(((${1}*100/${2}*100)/100))
@@ -101,7 +104,7 @@ ProgressBar() {
 # 1.2 Build progressbar strings and print the ProgressBar line
 # 1.2.1 Output example:
 # 1.2.1.1 Progress : [########################################] 100%
-printf "\rProgress : [${_done// /=}${_left// / }] ${_progress}%%"
+printf "\rProgress : ${BGBL}|${N}${_done// /${BGBL}$loadBar${N}}${_left// / }${BGBL}|${N} ${_progress}%%"
 }
 
 # "cmd & spinner [message]"
@@ -111,7 +114,7 @@ spinner() {
 	while [ -d /proc/$PID ]; do
 		h=$(((h+1)%4))
 		sleep 0.02
-		printf "\r$@ [${anim:$h:1}]"
+		printf "\rLoading [${anim:$h:1}]"
 	done
 }
 
@@ -179,20 +182,20 @@ AUTHOR=$(grep_prop author $MODDIR/module.prop)
 MODTITLE=$(grep_prop name $MODDIR/module.prop)
 
 # Colors
-G='\e[01;32m'    # GREEN
-R='\e[01;31m'    # RED
-Y='\e[01;33m'    # YELLOW
-B='\e[01;34m'    # BLUE
-V='\e[01;35m'    # VIOLET
-Bl='\e[01;30m'   # BLACK
-C='\e[01;36m'    # CYAN
-W='\e[01;37m'    # WHITE
-N='\e[00;37;40m' # How to use (example): echo "${G}example${N}"
-
+G='\e[01;32m'		# GREEN TEXT
+R='\e[01;31m'		# RED TEXT
+Y='\e[01;33m'		# YELLOW TEXT
+B='\e[01;34m'		# BLUE TEXT
+V='\e[01;35m'		# VIOLET TEXT
+Bl='\e[01;30m'		# BLACK TEXT
+C='\e[01;36m'		# CYAN TEXT
+W='\e[01;37m'		# WHITE TEXT
+BGBL='\e[1;30;47m'	# Background W Text Bl
+N='\e[0m'			# How to use (example): echo "${G}example${N}"
 # Remove colors if -nc or in ADB Shell
 [ -n "$1" -a "$1" == "-nc" ] && shift && NC=true
 [ "$NC" -o -n "$LOGNAME" ] && {
-	G=''; R=''; Y=''; B=''; V=''; Bl=''; C=''; W=''; N='';
+	G=''; R=''; Y=''; B=''; V=''; Bl=''; C=''; W=''; N=''; BGBL=''; loadBar='=';
 }
 
 # Divider (based on $MODTITLE, $VER, and $REL characters)
@@ -208,6 +211,7 @@ mod_head() {
 	echo "${W}$_bbname${N}"
 	echo "${Bl}$_bb${N}"
 	echo "$div"
+	[ -s $LOG ] && echo "Enter ${W}logs${N} to upload logs" && echo $div
 }
 
 #=========================== Main
@@ -224,12 +228,12 @@ Usage: $_name
    or: $_name [options]...
    
 Options:
-    -nc                        removes ANSI escape codes
-    -l [app|priv-app|vendor]   list system apps
-    -d [app folder name]       uninstall apps (use $_name -d -h 
-    -i [file]                  import config from file
-    -e [file]                  export current settings
-    -h                         show this message
+    -nc                              removes ANSI escape codes
+    -l [app|priv-app|vendor]         list system apps
+    -d [app label|app folder name]   uninstall apps (use $_name -d -h)
+    -i [file]                        import config from file
+    -e [file]                        export current settings
+    -h                               show this message
 EOF
 exit
 }
@@ -648,6 +652,7 @@ case "$1" in
 			abort "$(help_me)"
 		fi
 		c=1
+		echo ""
 		for i in $(seq 1 $((${#app_name[@]}-1))); do
 			[ ! "${app_label[$i]}" ] && app_label[$i]="null"
 			echo "$(echo ${app_name[$i]} | tr '_' ' ') - ${app_label[$i]} - $(echo ${app[$i]} ${privapp[$i]} ${venapp[$i]} | sed 's/\/system/./g')"
@@ -656,13 +661,22 @@ case "$1" in
 	-d) shift
 		[ ! "$1" ] && help_me
 		[ "$1" == "-h" ] && {
-			echo "$_name -d [system app folder/s]\ne.g. \"$_name -d Velvet LatinIME\"\n"
-			echo "To see the list of system apps and its info (its folder name \nin this situation) use \"$_name -l\" "
+			echo "$_name -d [system app label/s | system app folder/s]\ne.g. \"$_name -d com.google.android.youtube com.android.terminal Velvet LatinIME\"\n"
+			echo "To see the list of system apps and its info (its folder name or app label \nin this situation) use \"$_name -l\" "
 			exit
 		}
 		for i in "$@"; do
-			app_dir=$(find $SYSTEM/app $SYSTEM/priv-app $SYSTEM/vendor/app -name $i -type d)
-			[ ! "$app_dir" ] && abort "$i doesn't exist in $SYSTEM"
+			d_app_label=$(dumpsys package $i | grep "path:")
+			[ $? -gt 0 ] && app_dir=$(find $SYSTEM/app $SYSTEM/priv-app $SYSTEM/vendor/app -name $i -type d) || app_dir=$(echo $d_app_label | sed 's/.*path: //;s/\(.*\)\/.*/\1/')
+			[ ! "$app_dir" ] && { echo "$i doesn't exist in $SYSTEM"; ok=false; continue; } || {
+				[ $(echo $app_dir | grep "/system") ] && {
+					ok=true
+				} || {
+					echo "$i is not a system app"
+					ok=false
+					continue
+				}
+			}
 			[ -f $MODDIR$app_dir/.replace ] && echo "$i already uninstalled" && continue
 			echo "$i found in $app_dir"
 			name[0]=${app_dir##*/}; get_app_name $app_dir 0 2>$LOG
@@ -679,9 +693,9 @@ case "$1" in
 				} || echo " - not deleted"
 			fi
 		done
+		$ok || abort "error: Use \"$_name -d -h\" for help"
 		exit;;
 	-h|--help) help_me;;
-	*) help_me;;
 esac
 
 menu
