Change MOUNTPATH
Signed-off-by: Val Mandantes <mandantesv@gmail.com>

diff --git a/system/xbin/debloat b/system/xbin/debloat
--- a/system/xbin/debloat
+++ b/system/xbin/debloat
@@ -14,7 +14,7 @@ ls /data >/dev/null 2>&1 || { echo "$ID needs to run as root!"; echo "type 'su' 
 [ -f /data/adb/magisk/util_functions.sh ] && . /data/adb/magisk/util_functions.sh || { echo "util_functions.sh not detected!"; exit 1; }
 
 # Magisk Mod Directory
-MOUNTPATH="/sbin/.magisk/img"
+MOUNTPATH="/data/adb/modules"
 MODDIR="$MOUNTPATH/$ID"
 [ ! -d $MODDIR ] && { echo "Module not detected!"; exit 1; }
 
@@ -67,37 +67,32 @@ import_file=/cache/import-debloat.txt
 exclude_file=$MODDIR/exclude.list
 LISTFILE=/cache/debloat.list
 RESCAN=true
-MOUNT_LOOP=$(basename $(grep -m1 $MOUNTPATH /proc/mounts | awk '{print $1}'))
 
 [ $(getenforce) == "Permissive" ] && use_cmd=true || use_cmd=false
 [ $LOGNAME ] && use_cmd=true || use_cmd=false
 
 debloat_app() {
   [ "$1" == "n" ] && shift || get_cfg $1
-  if grep -w $DIR_APP /proc/mounts | grep -q $MOUNT_LOOP; then
-    echo "${R}${1}${N} Failed! $DIR_APP is mounted (by another Magisk Module)!"
-  else
-    echo "Uninstalling ${R}${1}${N} ($DIR_APP)" | tr '%_' ' '
-    sleep 0.4
-	[ ! -d $DIR_APP ] && DIR_APP=$(dumpsys package $PKG | grep "path:" | sed 's/.*path: //;s/\(.*\)\/.*/\1/' 2>/dev/null)
-	echo " App Label: ${G}$PKG${N}"
-	echo " App Dir: ${G}$DIR_APP${N}"
-	[ "$proceed" == "a" ] || {
-	  echo -n " Proceed? < (y)es | (n)o | (a)ll >: "
-	  read proceed
-	}
-	case "$proceed" in
-	  y|Y|a|A)  mktouch ${MODDIR}${DIR_APP}/.replace ${1}
-            $use_aapt && {
-              if $(dumpsys package $PKG | grep UPDATED_SYSTEM_APP >/dev/null); then
-                echo " - App is updated, uninstall updates in Settings App"
-              fi
-			}
-			echo "${R}${1}${N} uninstalled" | tr '%_' ' ';;
-	  n|N) echo "${R}${1}${N} cancelled" | tr '%_' ' ';;
-	  *) echo "Invalid!";;
-	esac
-  fi
+   echo "Uninstalling ${R}${1}${N} ($DIR_APP)" | tr '%_' ' '
+  sleep 0.4
+  [ ! -d $DIR_APP ] && DIR_APP=$(dumpsys package $PKG | grep "path:" | sed 's/.*path: //;s/\(.*\)\/.*/\1/' 2>/dev/null)
+  echo " App Label: ${G}$PKG${N}"
+  echo " App Dir: ${G}$DIR_APP${N}"
+  [ "$proceed" == "a" ] || {
+    echo -n " Proceed? < (y)es | (n)o | (a)ll >: "
+    read proceed
+  }
+  case "$proceed" in
+    y|Y|a|A)  mktouch ${MODDIR}${DIR_APP}/.replace ${1}
+             $use_aapt && {
+             if $(dumpsys package $PKG | grep UPDATED_SYSTEM_APP >/dev/null); then
+               echo " - App is updated, uninstall updates in Settings App"
+             fi
+		     }
+			 echo "${R}${1}${N} uninstalled" | tr '%_' ' ';;
+	n|N) echo "${R}${1}${N} cancelled" | tr '%_' ' ';;
+	*) echo "Invalid!";;
+  esac
 }
 
 get_cfg() {
